# Generated by Django 2.2.9 on 2020-02-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20200123_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remainig_invitations',
            new_name='remaining_invitations',
        ),
    ]
