# Generated by Django 2.2.9 on 2020-02-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20200208_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='rides_takes',
            new_name='rides_taken',
        ),
    ]
