# Generated by Django 2.2.9 on 2020-02-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_invitation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitation',
            managers=[
            ],
        ),
    ]
